apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-botscribe
  labels:
    app: gbv-botscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbv-botscribe
  template:
    metadata:
      labels:
        app: gbv-botscribe
    spec:
      containers:
      - name: gbv-botscribe
        image: localhost:32000/botscribe:registry
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "chatroach-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: BOTSCRIBE_HIGHWATER
          value: "500"
        - name: BOTSPINE_KAFKA_BROKERS
          value: "spinaltap-kafka:9092"
        - name: BOTSPINE_MESSAGE_TOPIC
          value: "chat-events"
      volumes:
        - name: keys
          secret:
            secretName: gbv-botscribe-keys
