apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-botscribe
  labels:
    app: gbv-botscribe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gbv-botscribe
  template:
    metadata:
      labels:
        app: gbv-botscribe
    spec:
      containers:
      - name: gbv-botscribe
        image: vlabresearch/botscribe:0.0.4
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-postgres"
        - name: CHATBASE_DATABASE
          value: "chatroach"
        - name: CHATBASE_USER
          value: "chatroach"
        - name: CHATBASE_PASSWORD
          value: ""
        - name: CHATBASE_HOST
          value: "chatroach-cockroachdb-public.default"
        - name: CHATBASE_PORT
          value: "26257"
        - name: KAFKA_TOPIC
          value: "chat-events"
        - name: KAFKA_GROUP_ID
          value: "botscribe-chatroach"
        - name: BOTSCRIBE_HIGHWATER
          value: "500"
      volumes:
        - name: keys
          secret:
            secretName: gbv-botscribe-keys
