apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbv-botscribe
  labels:
    app: gbv-botscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbv-botscribe
  template:
    metadata:
      labels:
        app: gbv-botscribe
    spec:
      containers:
      - name: gbv-botscribe
        image: vlabresearch/gbv-botscribe:0.0.1
        resources:
          requests:
            cpu: "100m"
            memory: "500Mi"
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: gbv-bot-envs
        env:
        - name: CHATBASE_BACKEND
          value: "@vlab-research/chatbase-gcs"
        - name: CHATBASE_BUCKET
          value: "gbv-chatbase-test"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "keys/key.json"
        - name: KAFKA_TOPIC
          value: "chat-events"
      volumes:
        - name: keys
          secret:
            secretName: gbv-botscribe-keys
